apiVersion: apps/v1
kind: Deployment
metadata:
  name: fingerprint-service
  namespace: stream-viewers
  labels:
    app: stream-viewer
    component: fingerprint-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stream-viewer
      component: fingerprint-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: stream-viewer
        component: fingerprint-service
    spec:
      containers:
      - name: fingerprint-service
        image: your-registry/fingerprint-service:latest
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        env:
        - name: PORT
          value: "3001"
        - name: FINGERPRINT_POOL_SIZE
          value: "5000"   # Reduced from 10000 to prevent high memory usage during startup
        - name: LOG_LEVEL
          value: "info"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 300Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /healthz
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 12  # Allow 60 seconds (12 * 5s) for startup
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: fingerprint-service
  namespace: stream-viewers
  labels:
    app: stream-viewer
    component: fingerprint-service
spec:
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    protocol: TCP
  selector:
    app: stream-viewer
    component: fingerprint-service
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fingerprint-service
  namespace: stream-viewers
  labels:
    app: stream-viewer
    component: fingerprint-service
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fingerprint-service
  minReplicas: 1
  maxReplicas: 3
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 60